import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useState } from 'react'
import { json } from 'stream/consumers'
import styles from '../styles/Home.module.css'
import { GetCharacterResult, Character } from '../types'

import LoginPage from './auth/login'

const Home: NextPage<{ characters: Character[] }> = ({ characters }) => {

  const [auth, setauth] = useState<boolean>(false);

  if (!auth) {
    return <LoginPage />
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {
        characters.map(character => {
          return <div key={character.id}>
            <Link href={`/characters/${character.id}`}>
              <a>
                <h3>
                  {character.name}
                </h3>
              </a>
            </Link>
            <Image
              src={character.image}
              width={200}
              height={200}
              alt={character.name}
            />
          </div>
        })
      }
    </div>
  )
}


export const getStaticProps: GetStaticProps = async (context) => {
  const res = await fetch('https://rickandmortyapi.com/api/character');
  const { results }: GetCharacterResult = await res.json();

  return {
    props: {
      characters: results,
    }
  }
}


export default Home;
